# Generated by Django 5.1.6 on 2025-03-31 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('type', models.CharField(choices=[('PROJECT_STATUS', 'Project Status'), ('USER_PERFORMANCE', 'User Performance'), ('TASK_OVERVIEW', 'Task Overview'), ('TIME_TRACKING', 'Time Tracking'), ('CUSTOM', 'Custom Report')], max_length=50, verbose_name='Report Type')),
                ('access_level', models.CharField(choices=[('viewer', 'Viewer'), ('general_admin', 'General admin'), ('project_admin', 'Project admin'), ('project_member', 'Project member')], max_length=20, verbose_name='Access level')),
                ('filters', models.JSONField(blank=True, help_text='User-defined filters for custom reports', null=True, verbose_name='Filters')),
                ('content', models.JSONField(help_text='Time report data for later viewing or export', verbose_name='Content')),
                ('auto_send', models.BooleanField(default=False, verbose_name='Auto Send')),
                ('schedule', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True, verbose_name='Send Schedule')),
                ('last_send_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Send At')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archive_at', models.DateTimeField(blank=True, null=True, verbose_name='Archive At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ('-created_at',),
            },
        ),
    ]
