# Generated by Django 5.1.6 on 2025-03-31 21:42

import apps.report.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='schedule',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True, validators=[apps.report.validators.validate_schedule], verbose_name='Send Schedule'),
        ),
    ]
