# Generated by Django 5.1.6 on 2025-02-12 14:28

import apps.account.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('title', models.CharField(choices=[('viewer', 'Viewer'), ('general_admin', 'General Admin'), ('project_admin', 'Project Admin'), ('project_member', 'Project Member')], default='viewer', max_length=40, unique=True, verbose_name='Access Title')),
            ],
            options={
                'verbose_name': 'دسترسی',
                'verbose_name_plural': 'دسترسی ها',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=225, null=True, verbose_name='ایمیل')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('is_used_free_subs', models.BooleanField(default=False, verbose_name='از اشتراک رایگان استفاده شده است ؟')),
                ('token', models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='توکن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('accesses', models.ManyToManyField(blank=True, related_name='user', to='account.accessmodel', verbose_name='دسترسی ها')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('melli_code', models.CharField(blank=True, max_length=10, null=True, validators=[apps.account.validators.validate_digit_type], verbose_name='کدملی')),
                ('gender', models.CharField(blank=True, choices=[('m', 'مرد'), ('f', 'زن')], max_length=8, null=True, verbose_name='جنسیت')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('place_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام مجموعه')),
                ('province', models.CharField(blank=True, max_length=64, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='شهر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/profiles/', verbose_name='تصویر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
    ]
