# Generated by Django 5.1.6 on 2025-02-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accessmodel_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessmodel',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
