# Generated by Django 5.1.6 on 2025-03-31 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('type', models.CharField(choices=[('IMPORTANT_PROJECT_MESSAGE', 'Important Project Message'), ('PROJECT_REPORT', 'Project Report'), ('TEAM_INVITATION', 'Team Invitation')], max_length=130, verbose_name='email type')),
                ('title', models.CharField(max_length=130, verbose_name='email title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/notification/email/', verbose_name='images')),
                ('kwargs', models.JSONField(blank=True, null=True, verbose_name='keyword args')),
                ('send_email', models.BooleanField(default=True, verbose_name='send email')),
                ('is_showing', models.BooleanField(default=True, verbose_name='Is showing')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to=settings.AUTH_USER_MODEL, verbose_name='to user')),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SMSNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('type', models.CharField(choices=[('ACCOUNT_REGISTRATION', 'Account Registration'), ('PASSWORD_REMINDER', 'Password Reminder'), ('MEETING_REQUEST', 'Meeting Request'), ('ADDED_TO_PROJECT', 'added to project')], max_length=130, verbose_name='sms type')),
                ('title', models.CharField(max_length=130, verbose_name='sms title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('kwargs', models.JSONField(blank=True, null=True, verbose_name='keyword args')),
                ('send_sms', models.BooleanField(default=True, verbose_name='send sms')),
                ('is_showing', models.BooleanField(default=True, verbose_name='Is showing')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to=settings.AUTH_USER_MODEL, verbose_name='to user')),
            ],
            options={
                'verbose_name': 'SMS Notification',
                'verbose_name_plural': 'SMS Notifications',
                'ordering': ('-id',),
            },
        ),
    ]
